#!/bin/sh -eux

image_name='ghcr.io/dwsr/carvel-tools'


docker build \
  --platform linux/arm64 \
  --tag "${image_name}:latest-arm64" \
  --build-arg IMGPKG_VERSION=v0.33.0 \
  --build-arg IMGPKG_CHECKSUM=08c8eafd44a0a51c47a06d9f5146e8659b88878e6f053fb1a6cc7eeed7f8019f \
  --build-arg KBLD_VERSION=v0.35.0 \
  --build-arg KBLD_CHECKSUM=54e92ff92e66a4b86d7768019cb3b40c87e0e6084380c9a765679b2d342fc4f8 \
  .

docker push "${image_name}:latest-arm64"

docker build \
  --platform linux/amd64 \
  --tag "${image_name}:latest-amd64" \
  --build-arg IMGPKG_VERSION=v0.33.0 \
  --build-arg IMGPKG_CHECKSUM=10a8327490ca3dbfa3d00f90ae442838d364e4d7d158786e94aa1ff0438dab27 \
  --build-arg KBLD_VERSION=v0.35.0 \
  --build-arg KBLD_CHECKSUM=1c3f0e4171063eef70cdabf1730d3557af992aeafb423755e71e9d5f1aea2c9b \
  .

docker push "${image_name}:latest-amd64"


docker manifest create "${image_name}:latest" "${image_name}:latest-arm64" "${image_name}:latest-amd64" --amend

docker manifest push "${image_name}:latest"
